#!/bin/sh

echo "\nStarting Program - SDNBCQKD\n"

echo "  ===================== TOPOLOGY ======================"
echo "  |                                                   |"
echo "  |                   un-encrypted                    |"
echo "  |   -----       -----    /\    -----      -----     |"
echo "  |  |  N1 |-----| SW1 | <    > | SW2 |----|  N2 |    |"
echo "  |   -----       -----    \/    -----      -----     |"
echo "  |                  \    encr     /                  |"
echo "  |                   \           /                   |"
echo "  |                    \         /                    |"
echo "  |                   -------------                   |"
echo "  |                  |  SDN CTRL   |                  |"
echo "  |                   -------------                   |"
echo "  |                                                   |"
echo "  =====================================================\n"

echo "Please tell me which option you want to execute, by pressing the corresponding button:"
echo " [1] - Switch Channel to un-encrypted mode"
echo " [2] - Switch channel to encrypted mode"
echo ""

read -p 'Enter here: ' ACTION

if [ $ACTION -eq 1 ] 
then
	echo "\nExecuting SDN command to turn off encryption."
	curl -X GET http://localhost:8080/channel/1/1
elif [ $ACTION -eq 2 ]
then 
	echo "\nExecuting command to turn on encryption"
	curl -X GET http://localhost:8080/channel/1/2
else
	echo "\nAction not supported!!!"
fi


echo "\nFinishing Program - SDNBCQKD\n"